unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g history-limit 20000
set -g mouse on
setw -g mode-keys vi
set -g xterm-keys on

bind -r H resize-pane -L 1
bind -r J resize-pane -D 1
bind -r K resize-pane -U 1
bind -r L resize-pane -R 1

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi i send -X cancel
bind-key V display-popup -E "tmux capture-pane -p -S - | nvim -R -c 'set nomodifiable noswapfile nobuflisted' -"
bind-key N display-popup -E "$SHELL"

set -g @mytitle 'victor@wsl'
set -g status-right '#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}(#{=21:@mytitle}) %H:%M %d-%b-%y'
set -g pane-border-lines double

# rendering
set -g escape-time 0
set -g focus-events on
set -sg terminal-overrides ',*:Sync'
set -as terminal-features ',*:RGB'
